# Generated by Django 3.2.12 on 2024-03-03 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['name'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_group_users',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_group_users',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Студенты группы'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_student',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_student',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное количество студентов'),
        ),
        migrations.AddField(
            model_name='product',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_products', to=settings.AUTH_USER_MODEL, verbose_name='Студент/ы продукта'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.product', verbose_name='Группы продукта'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='api.product', verbose_name='Урок продукта'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(verbose_name='Ссылка на видео урок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_products', to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Дата и время старта продукта'),
        ),
    ]
