# Generated by Django 3.2.12 on 2024-03-03 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20240303_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_student',
            field=models.PositiveIntegerField(default=10, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_products', to=settings.AUTH_USER_MODEL, verbose_name='Студенты продукта'),
        ),
    ]
