# Generated by Django 3.2.12 on 2024-03-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cost_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creator',
            new_name='author',
        ),
    ]
